- hosts: localhost
  gather_facts: no
  tasks:
    - name: outer block
      block:
        - name: EXPECTED FAILURE inner block
          block:
            - name: ansible_failed_task works
              fail:
          always:
            - debug:
      rescue:
        - debug:
            msg: "{{ ansible_failed_task.action }}"
