docs:
  - uri module now has correct example with failed_when
